### PR TITLE
Fixing tests with changes to github

### PR DESCRIPTION
**Pull request by vince62s**

### CODE REVIEW

**Comment by vince62s** [comment]
@homink I need your help here.
While updating some small stuff in tests, suddenly your test for wav2vec is failing. I thought it was linked to my change to HF's transformers version but I reverted it in this PR and it is still failing.
Can you please have a look?

**Comment by homink** [comment]
@vince62s I think this line caused the filling [here](https://github.com/OpenNMT/CTranslate2/actions/runs/6881707249/job/18720798034?pr=1549#step:9:242). This is just about the model saving and I am not sure how come this caused that fail. I will check if the latest CTranslate2 version still works for wav2vec2 testing.

**Comment by vince62s** [comment]
I will force torch==2.1.0 in tests just saw they released 2.1.1 would like to avoid mismatch.

**Comment by vince62s** [comment]
check this too
https://github.com/OpenNMT/CTranslate2/actions/runs/6881707249/job/18720798034?pr=1549#step:9:268
I thought the state_dict may have changed with transformerrs version but was not that.

**Comment by homink** [comment]
I installed [CTranslate2 3.21.0](https://github.com/OpenNMT/CTranslate2/releases/tag/v3.21.0) and ran it as shown below without any errors. It's really odd.

```
>>> import torch
>>> import transformers
>>> import ctranslate2
>>> import os
>>> import numpy as np
>>> model_name="facebook/wav2vec2-large-robust-ft-swbd-300h"
>>> expected_transcription = [
...                     "MISTER QUILTER IS THE APOSSEL OF THE MIDDLE CLASSES AND"
...                     " WE ARE GLAD TO WELCOME HIS GOSPEL",
...                 ]
>>> converter = ctranslate2.converters.TransformersConverter(
...     model_name, load_as_float16="int8"
... )
>>> output_dir = converter.convert("ctranslate2_model")
>>> w2v2_model = transformers.Wav2Vec2ForCTC.from_pretrained(model_name)
>>> del w2v2_model.wav2vec2.encoder.layers
>>> del w2v2_model.wav2vec2.encoder.layer_norm
>>> torch.save(w2v2_model, output_dir + "/wav2vec2_partial.bin")
>>> w2v2_processor = transformers.Wav2Vec2Processor.from_pretrained(model_name)
>>> torch.save(w2v2_processor, output_dir + "/wav2vec2_processor.bin")
>>> device = "cuda" if os.environ.get("CUDA_VISIBLE_DEVICES") else "cpu"
>>> cpu_threads = int(os.environ.get("OMP_NUM_THREADS", 0))
>>> w2v2_model = torch.load(output_dir + "/wav2vec2_partial.bin").to(device)
>>> w2v2_processor = torch.load(output_dir + "/wav2vec2_processor.bin")
>>> ct2_w2v2_model = ctranslate2.models.Wav2Vec2(
...     output_dir,
...     device=device,
...     device_index=[0],
...     compute_type="int8",
...     intra_threads=cpu_threads,
...     inter_threads=1,
... )
>>> speech_array = np.load("/nobackup/hkwon2/3rdParty/CTranslate2_20231024/tests/data/audio/mr_quilter.npy")
>>> input_values = w2v2_processor(
...     speech_array,
...     padding=True,
...     return_tensors="pt",
...     sampling_rate=16000,
... ).input_values
2023-11-15 20:48:06.563481: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
>>> with torch.no_grad():
...     extract_features = w2v2_model.wav2vec2.feature_extractor(
...         input_values.to(w2v2_model.device)
...     ).transpose(1, 2)
...     hidden_states, extract_features = w2v2_model.wav2vec2.feature_projection(
...         extract_features
...     )
...     position_embeddings = w2v2_model.wav2vec2.encoder.pos_conv_embed(
...         hidden_states
...     )
...     hidden_states = position_embeddings + hidden_states
...     # hidden_states = w2v2_model.encoder.dropout(hidden_states)
...     # Dropout(p=0.0, inplace=False) bypassed
... 
>>> if ct2_w2v2_model.device == "cuda":
...     hidden_states = hidden_states.cpu()
... else:
...     hidden_states.numpy()
... 
array([[[ 0.1693899 ,  2.2634823 , -1.2306788 , ..., -3.899944  ,
         -3.0574274 ,  6.486378  ],
        [ 1.0232238 ,  0.15435292, -1.3267676 , ..., -4.3173304 ,
          0.4245553 ,  4.386175  ],
        [ 2.9067817 ,  2.274394  , -2.0829062 , ...,  1.2998496 ,
         -0.8333913 ,  1.6946803 ],
        ...,
        [ 1.6564841 ,  1.2391592 , -3.0736432 , ...,  6.115755  ,
          5.7456884 ,  5.0317454 ],
        [ 2.7244632 ,  1.0191028 , -1.9882839 , ...,  9.378099  ,
         -0.4236964 ,  3.1421895 ],
        [ 2.2139602 ,  2.5174143 , -3.9946754 , ...,  3.1492426 ,
         -0.53378797,  5.6609497 ]]], dtype=float32)
>>> hidden_states = np.ascontiguousarray(hidden_states)
>>> hidden_states = ctranslate2.StorageView.from_array(hidden_states)
>>> to_cpu = (
...     ct2_w2v2_model.device == "cuda" and len(ct2_w2v2_model.device_index) > 1
... )
>>> ct2_output = ct2_w2v2_model.encode(
...     hidden_states,
...     to_cpu=to_cpu,
... )  # 24 x Wav2Vec2EncoderLayerStableLayerNorm processed
>>> if ct2_w2v2_model.device == "cuda":
...     hidden_states = torch.as_tensor(
...         ct2_output,
...         device=ct2_w2v2_model.device,
...     )
... else:
...     hidden_states = torch.as_tensor(
...         np.array(ct2_output),
...         dtype=torch.float32,
...         device=ct2_w2v2_model.device,
...     )
... 
>>> encoder_outputs = transformers.modeling_outputs.BaseModelOutput(
...     last_hidden_state=hidden_states,
...     hidden_states=None,
...     attentions=None,
... )
>>> hidden_states = encoder_outputs[0]
>>> outputs = transformers.modeling_outputs.Wav2Vec2BaseModelOutput(
...     last_hidden_state=hidden_states,
...     extract_features=extract_features,
...     hidden_states=encoder_outputs.hidden_states,
...     attentions=encoder_outputs.attentions,
... )
>>> hidden_states = outputs[0]
>>> # hidden_states = w2v2_model.dropout(hidden_states)
>>> # Dropout(p=0.0, inplace=False) bypassed
>>> with torch.no_grad():
...     logits = w2v2_model.lm_head(hidden_states.to(torch.float32))[0]
... 
>>> predicted_ids = torch.argmax(logits, dim=-1)
>>> transcription = w2v2_processor.decode(predicted_ids, output_word_offsets=True)
>>> assert transcription[0] == expected_transcription[0]
```

**Pull request closed without merging**
