### PR TITLE
fix: implement llama3 RoPE scaling type and fix converter

### LINKED ISSUE #1745: Llama 3.1 support please?
Hello again, if you plan on supporting LLama3.1 please note that it requires a new category of ROPE scaling.  Thanks!

https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct/blob/main/config.json

### PR DESCRIPTION
**Pull request by ebraraktas**
Fixes #1745 .

Implementation is ported from [tranformers](https://github.com/huggingface/transformers/blob/14ee2326e51cb210cec72f31b248cb722e9d5d1f/src/transformers/modeling_rope_utils.py#L298)

### CODE REVIEW

**Comment by ebraraktas** [comment]
While implementing this, I saw that rotary embedding layer is shared among layers of Llama3 and huggingface implementation is refactored to use that shared one. Maybe we can implement this feature in ctranslate2 to reduce memory usage.

**Comment by minhthuc2502** [comment]
Hello, thank you for your PR. I will fix the CI soon and you can rebase on the master.  What do you mean ``rotary embedding layer is shared among layers of Llama3 and huggingface implementation``. Can you add the link here?

**Comment by ebraraktas** [comment]
Thanks for the comment, I will rebase once you fix it. @minhthuc2502 

For RoPE sharing:
* `rotary_emb` will be removed from `LlamaAttention`, see [this comment](https://github.com/huggingface/transformers/blob/c1aa0edb48217f416f4bbe6e3a9db1500284513b/src/transformers/models/llama/modeling_llama.py#L361-L362)
* `position_embeddings` (tuple of `cos` and `sin`) will be generated from input embeddings at the beginning of inference [inside](https://github.com/huggingface/transformers/blob/c1aa0edb48217f416f4bbe6e3a9db1500284513b/src/transformers/models/llama/modeling_llama.py#L976-L977) `LlamaModel.forward` and passed to the layers using it.
* And `position_embeddings` will be passed as an input to `LlamaAttention.forward`, implemented [here](https://github.com/huggingface/transformers/blob/c1aa0edb48217f416f4bbe6e3a9db1500284513b/src/transformers/models/llama/modeling_llama.py#L404-L413)

**Comment by minhthuc2502** [comment]
Ah I understand your point. Actually, we can keep the current architecture because It requires more changes than HF to do this.

**Comment by minhthuc2502** [comment]
Could you rebase on the master branch? please

**Comment by ebraraktas** [comment]
As in [this PR](https://github.com/OpenNMT/CTranslate2/pull/1600#issuecomment-2274152018), no space left error occurred during docker step of the CI/CD.

**Pull request merged**
