### PR TITLE
Update doc AWQ quantization

### PR DESCRIPTION
**Pull request by minhthuc2502**

### CODE REVIEW

**Comment by minhthuc2502** [comment]
#1776

**Comment by BBC-Esq** [comment]
It's minimal but something for devs to at least go by...BTW, any progress on exposing the different documentation version based on ctranslate2 release versions?

**Comment by minhthuc2502** [comment]
The documentation will be updated after merging the PR.

**Comment by minhthuc2502** [comment]
> It's minimal but something for devs to at least go by...BTW, any progress on exposing the different documentation version based on ctranslate2 release versions?

The documentation will be udpated after merging the PR.

**Pull request merged**
