### PR TITLE
Do not mark relative position as optional when they are required

### PR DESCRIPTION
**Pull request by guillaumekln**

### CODE REVIEW

**Comment by vince62s** [comment]
@guillaumekln 
I got an issue when converting a onmt-py LM to CT2:
python3 tools/release_model.py --model lm-de.xl.pt --format ctranslate2 --output "lm-de.xl_ct2"
Traceback (most recent call last):
  File "tools/release_model.py", line 6, in <module>
    main()
  File "OpenNMT-py/onmt/bin/release_model.py", line 34, in main
    converter.convert(opt.output, force=True,
  File "/usr/local/lib/python3.8/dist-packages/ctranslate2/converters/converter.py", line 89, in convert
    model_spec = self._load()
  File "/usr/local/lib/python3.8/dist-packages/ctranslate2/converters/opennmt_py.py", line 155, in _load
    return _get_model_spec_lm(
  File "/usr/local/lib/python3.8/dist-packages/ctranslate2/converters/opennmt_py.py", line 105, in _get_model_spec_lm
    set_transformer_decoder(
TypeError: set_transformer_decoder() got multiple values for argument 'with_encoder_attention'

any clue ?

**Comment by guillaumekln** [comment]
Right, this PR broke the conversion of LM trained with OpenNMT-py. We should add tests for that (I'm looking to train a small LM on a dummy dataset).

@funboarder13920 It looks like you already have a fix, do you want to open a PR?

In the meantime, you can install version `ctranslate2==2.19.0` which should work fine.

**Comment by vince62s** [comment]
in the meantime since I don't use relative_position if I remove it from line 108 here, it works fine, right ?

def _get_model_spec_lm(opt, variables, src_vocabs, tgt_vocabs, num_source_embeddings):
    """Creates a model specification from the model options."""
    with_relative_position = getattr(opt, "max_relative_positions", 0) > 0
    activation_fn = getattr(opt, "pos_ffn_activation_fn", "relu")
    num_heads = getattr(opt, "heads", 8)

    model_spec = transformer_spec.TransformerDecoderModelSpec(
        opt.dec_layers,
        num_heads,
        activation=_SUPPORTED_ACTIVATIONS[activation_fn],
    )

    set_transformer_decoder(
        model_spec.decoder,
        variables,
        with_encoder_attention=False,
    )

    for tgt_vocab in tgt_vocabs:
        model_spec.register_vocabulary(tgt_vocab)

    return model_spec

**Comment by guillaumekln** [comment]
> in the meantime since I don't use relative_position if I remove it from line 108 here, it works fine, right ?

Yes.

**Pull request merged**
