### PR TITLE
Initial support of language models

### LINKED ISSUE #740: Support more general transformers (examples) such as GPT2?
Support more general transformers (examples) such as GPT2?

### PR DESCRIPTION
**Pull request by guillaumekln**
Add a high-level class `Generator` to run generative language models and a converter for OpenAI GPT-2.

Closes #740.

### CODE REVIEW

**Comment by guillaumekln** [comment]
Hi @funboarder13920, do you have some time to help with this PR? It would be helpful if you can try to extend the OpenNMT-py converter for your GPT model and check if it model is running properly. Then you could contribute the converter changes. Other feedbacks are also welcome!

**Comment by funboarder13920** [comment]
Hello, I will look into it on Tuesday.

**Comment by funboarder13920** [comment]
Hello Guillaume, I totally forgot to do it, I'm trying right now

**Comment by funboarder13920** [comment]
I was able to convert the model but the output of the inference is composed of repetitions of input tokens, which is not the expected output.
I was not able to find out what is wrong. I investigated the vocabulary, the embedding and the order of execution of modules in the decoder but didn't find anything suspicious.

**Comment by guillaumekln** [comment]
Does the OpenNMT-py model start the decoder with the token `<s>`? If yes, it should also be added to the start tokens passed to the generator. Can you check that?

**Comment by funboarder13920** [comment]
Indeed, I didn't insert the start token. I will push the converter this afternoon.

**Pull request merged**
