### PR TITLE
Add a minimal CI job for Windows and fix compilation

### LINKED ISSUE #370: Compilation issues with MSVC
Compilation with MSVC is no longer successful. I was able to spot this in `cpu_isa.h`:

```C++
#define SINGLE_ARG(...) __VA_ARGS__
#ifdef CT2_WITH_CPU_DISPATCH
#if defined(__x86_64__)
#  define CPU_ISA_DISPATCH(STMTS)                             \
  switch (cpu::get_cpu_isa()) {                               \
    CPU_ISA_CASE(cpu::CpuIsa::AVX2, SINGLE_ARG(STMTS))        \
    CPU_ISA_CASE(cpu::CpuIsa::AVX, SINGLE_ARG(STMTS))         \
    CPU_ISA_DEFAULT(cpu::CpuIsa::GENERIC, SINGLE_ARG(STMTS))  \
  }
```
which leaves `CPU_ISA_DISPATCH` undefined in `dequantize_cpu.cc`. The following patch seems to fix this and moves compilation further

```C++
< #if defined(__x86_64__)

> #if defined(__x86_64__) || defined( _WIN64)
```

But then it fails with a ton of unresolved external symbol linker errors.

I will look further into this during the weekend.

### PR DESCRIPTION
**Pull request by guillaumekln**
Fixes #370.

### CODE REVIEW

**Comment by guillaumekln** [comment]
@keichi Can you help reviewing this PR?

**Comment by guillaumekln** [comment]
This is breaking compilation with `-DENABLE_CPU_DISPATCH=OFF`. Need to revise the changes.

**Comment by panosk** [comment]
Hi @guillaumekln 

How about we move the definitions outside the `ENABLE_CPU_DISPATCH` conditional and check a variable instead? The following change seems to work with `ENABLE_CPU_DISPATCH` set to `ON` or `OFF`:

```CMake
if (CMAKE_SYSTEM_PROCESSOR MATCHES "(x86_64)|(amd64)|(AMD64)")
  add_definitions(-DCT2_X86_BUILD)
  set(BUILD_ARCH "x86_64")
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "(arm64)|(aarch64)")
  add_definitions(-DCT2_ARM64_BUILD)
  set(BUILD_ARCH "arm64")
endif()

if(ENABLE_CPU_DISPATCH)
  message(STATUS "Compiling for multiple CPU ISA and enabling runtime dispatch")
  add_definitions(-DCT2_WITH_CPU_DISPATCH)
  if(BUILD_ARCH MATCHES "x86_64")
    if(WIN32)
      ct2_compile_kernels_for_isa(avx "/arch:AVX")
      ct2_compile_kernels_for_isa(avx2 "/arch:AVX2")
    else()
      ct2_compile_kernels_for_isa(avx "-mavx")
      ct2_compile_kernels_for_isa(avx2 "-mavx2")
    endif()
  elseif(BUILD_ARCH MATCHES "arm64")
    ct2_compile_kernels_for_isa(neon "-DUSE_NEON")
  endif()
endif()
```

**Comment by guillaumekln** [comment]
Yes, exactly.

**Comment by guillaumekln** [comment]
Let's merge this and prepare a new release.

**Pull request merged**
