### PR TITLE
correctly determine INTEL_ROOT_DEFAULT using MKLROOT env variable

### PR DESCRIPTION
**Pull request by alexlnkp**
As mentioned in the issue #1703 , `MKLROOT` env variable is set to `/opt/intel/oneapi/mkl/latest`, which makes sense. However, `CMakeLists.txt` tries to find the root of INTEL by going one dir up. `set(INTEL_ROOT_DEFAULT $ENV{MKLROOT}/..`. This wouldn't work, as the `MKLROOT` points to the `latest`, not `oneapi`. Therefore, to fix this - it's better to go 3 directories up, so that if `MKLROOT` is `/opt/intel/oneapi/mkl/latest`, it would correctly point to the root of INTEL.

### CODE REVIEW

**Comment by minhthuc2502** [comment]
Hello, this change will break the compilation on Windows. For the environment like Arch, you can set variable environment like ``INTELROOT`` or ``MKLROOT`` to make it work as you did in the issue. No PR is needed.

**Comment by alexlnkp** [comment]
> Hello, this change will break the compilation on Windows. For the environment like Arch, you can set variable environment like `INTELROOT` or `MKLROOT` to make it work as you did in the issue (this action is expected for certain OS). No PR is needed.

I mean, i could add a check for the OS and then check the paths, not sure if this would help anyone but me though.
I made this PR for people like me, who used `pacman` and `yay` to install all of the stuff the CTranslate2 needs, so i believe that this idea is more or less valid for at least the arch users.
Please let me know if some of the suggestions i made are valid.

**Comment by minhthuc2502** [comment]
If you don't set anything, ``INTEL_ROOT_DEFAULT`` will be ``/opt/intel`` . Otherwise, in your case, ``MKLROOT`` env variable is set to ``/opt/intel/oneapi/mkl/latest``, then you set ``set(INTEL_ROOT_DEFAULT $ENV{MKLROOT}/../../..)``, the ``INTEL_ROOT_DEFAULT`` would be ``/opt/intel``. Something I missed here?

**Comment by alexlnkp** [comment]
> If you don't set anything, `INTEL_ROOT_DEFAULT` will be `/opt/intel` . Otherwise, in your case, `MKLROOT` env variable is set to `/opt/intel/oneapi/mkl/latest`, then you set `set(INTEL_ROOT_DEFAULT $ENV{MKLROOT}/../../..)`, the `INTEL_ROOT_DEFAULT` would be `/opt/intel`. Something I missed here? Why you have to set MKLROOT?

That's the neat part! I didn't set `MKLROOT`. The package which is used to install the intel MKL stuff sets the env variable `MKLROOT` automatically via the INTEL's shell script, that was the main cause of the #1703 .
The shell script in question is `/opt/intel/oneapi/mkl/latest/env/vars.sh`

**Comment by alexlnkp** [comment]
> I see, You can do like this:
> 
> ```
> elseif(DEFINED ENV{MKLROOT})
>   if(WIN32)
>     set(INTEL_ROOT_DEFAULT $ENV{MKLROOT}/..)
>   else()
>    # Other system like arch set env MKLROOT by default
>    set(INTEL_ROOT_DEFAULT $ENV{MKLROOT}/../../..) 
> ```

Alrighty, i'll do that.
Though, do you want me to squash this change into previous commit so it's just a single commit PR or should i just have 2 commits here?

**Comment by minhthuc2502** [comment]
Don't worry about squash. I'll do when merge it.

**Pull request merged**
